title: "[Your Project Title]"
labels: ["demo"]
body:
  - type: markdown
    attributes:
      value: |
        Tell the Nillion developer community about your project:
  - type: dropdown
    id: category
    attributes:
      label: Show and tell project type
      options:
        - Nucleus Program Team (FE)
        - Novel Nada Program Example
        - Builder Bounty Submission
        - Hackathon Project Submission
        - Community Builder
        - Other
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: Github Repo Link
    validations:
      required: true
  - type: input
    id: video
    attributes:
      label: Video Walkthough Link
  - type: textarea
    id: description
    attributes:
      label: Project Description
      description: What did you build?
      value: |
        We built...
      render: bash
    validations:
      required: true
  - type: textarea
    id: problems-solved
    attributes:
      label: What problems does your project solve? How does it preserve privacy for users?
      value: |
        - 
        -
        -
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: nillion-usage
    attributes:
      label: How does the project use Nillion? Describe and link to any Nada programs
      value: |
        We used Nillion for...
        
        *Nada program link(s)*
        - 
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: feedback
    attributes:
      label: Is there anything else you want to share?
      description: Feature requests, bugs encountered, any help or support you need from Nillion to keep building?
  - type: textarea
    id: social-handles
    attributes:
      label: Optional - Link your project and team members' social handles
      placeholder: "https://twitter.com/nillionnetwork"
  - type: textarea
    id: eth-address
    attributes:
      label: Optional - Team ETH Address(es)
      value: |
        - 0x...
        - 0x...
  - type: markdown
    attributes:
      value: | 
        ### Thank you!
        Thanks for sharing your project with the Nillion developer community through show and tell! 
          
        ### Next Steps

        - 📲 Share your Show and Tell post on socials and tag [@NillionNetwork](https://twitter.com/nillionnetwork)
        - ⭐️ Want to see your project included in the Nillion Showcase of awesome open source projects? Follow [PR instructions here](https://docs.nillion.com/showcase#add-your-project-to-the-list)
        - 🧢 Want to earn exclusive Nillion swag? [Provide developer feedback here](https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ2g8w5axKPSxDb7I6kTPsuSsZwdrxTruNDESqbgilOneHDhb5bJW4fyt2yKwG2Xaj8j--LfpkKB)
